CC = gcc
CXX = g++

CFLAGS = -g -Wall
CXXFLAGS = -g -Wall

.PHONY: default
default: http-server

# Header Dependancy

http-server.o:

.PHONY: clean
clean: 
	rm -f http-server.o http-server

.PHONY: all
all: clean default
