CC = gcc
CXX = g++

CFLAGS = -g -Wall
CXXFLAGS = -g -Wall


.PHONY: default
default: http-client

http-client:

#Header Dependancy

http-client.o:

.PHONY: clean
clean:
	rm -f http-client.o http-client

.PHONY: all
all: clean default
